version: '3.8'

services:
  chat-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-server
    command: ./server
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - nats
    environment:
      - NATS_URL=nats://nats:4222
      - REDIS_URL=redis:6379
    restart: always

  chat-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-client
    command: ./client
    depends_on:
      - chat-server
    environment:
      - SERVER_ADDRESS=chat-server:8080
    stdin_open: true  # Keep container open for user input
    tty: true         # Enable terminal for interactive input

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: always

  nats:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    command: ["-js"]
    restart: always
